### ISSUE TITLE
Empty space at the beginning and at the end?

### ISSUE THREAD

**Issue by gerchicov-bp** [stefanceriu/SCSafariPageController#1]
I develop a similar component but based on iCarousel and it is a problem for me too. Safari has no such big empty spaces.

**Comment by stefanceriu** [comment]
It's not a problem at all, just the way I configured the zoomed out layouter:

```objc
- (UIEdgeInsets)contentInsetForPageViewController:(SCPageViewController *)pageViewController
{
	self.contentInset = UIEdgeInsetsMake(50.0f, 50.0f, 0.0f, 0.0f);
	return self.contentInset;
}
```

**Comment by gerchicov-bp** [comment]
Maybe I can't understand how to do that. I set it to ```UIEdgeInsetsMake(-100.0f, 50.0f, -100.0f, 0.0f);``` and ran on iPhone 6 simulator.
It seems now it breaks the animation and scrolling from the bottom to the top (to the first view) temporarily breaks the animation until the content stops scrolling.

**Comment by stefanceriu** [comment]
Content insets are also used to increase the angle of the pages when scrolling out of bounds. Now that you're using negative values you might want to fix that bit here:

```objc
CGFloat angle = 30.0f + MIN(numberOfPages * 5.0f, 30.0f);
if(contentOffset.y < -self.contentInset.top) {
	angle += (ABS(contentOffset.y) - self.contentInset.top) / 9.0f;
}
```
